name: Package and release (cataclysm alpha)
# This workflow automatically creates an alpha release when it runs on push to main, as there is no tag information available.

on:
  push:
    # use tag action if using this workflow on main repo
    branches:
      - working-trunk
      
# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "release" is a job, you can name it anything you want
  release:
    # we can run our steps on pretty much anything, but the "ubuntu-latest" image is a safe bet
    runs-on: ubuntu-latest
    
    environment: packager + uploader # https://github.com/vysci/LFG-Bulletin-Board/settings/environments
    env:
      # "GITHUB_TOKEN" is a secret always provided to the workflow
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }} 
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

    # "steps" holds a list of all the steps needed to package and release our AddOn
    steps:

      # we first have to clone the AddOn project, this is a required step
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # gets git history for changelogs

      # once cloned, we just run the GitHub Action for the packager project
      - name: Package and release
        uses: BigWigsMods/packager@v2.3.1
        with:
          args: -g cata -n "{package-name}-{release-type}-{project-abbreviated-hash}"

      # Release as Alpha/Beta on dev working branch
      # move this to a tag action at somepoint
      - name: create GIT_TAG env variable
        run: echo "GIT_TAG=`echo $(git tag --points-at HEAD)`" >> $GITHUB_ENV

      - name: Create alpha github release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(env.GIT_TAG, 'alpha') || startsWith(env.GIT_TAG, 'beta')}}
        with:
          tag_name: ${{ env.GIT_TAG }}
          files: ./.release/*.zip
          draft: false
          prerelease: true
